/** @author David Hdez */
// internal imports
import type { TrackingEventInterface } from "@/interfaces/TrackingEventInterface";

export const trackingEventSeeder: TrackingEventInterface[] = [
  {
    id: 1,
    packageId: 1,
    fromWarehouseId: 1,
    toWarehouseId: 2,
    timestamp: new Date("2026-03-10T08:00:00"),
    previousStatus: "Pending",
    newStatus: "In Transit",
    description: "Package picked up from Central Hub and dispatched to West Coast Depot.",
  },
  {
    id: 2,
    packageId: 1,
    fromWarehouseId: 2,
    toWarehouseId: 3,
    timestamp: new Date("2026-03-11T14:30:00"),
    previousStatus: "In Transit",
    newStatus: "In Transit",
    description: "Transferred from West Coast Depot to East Distribution center.",
  },
  {
    id: 3,
    packageId: 2,
    fromWarehouseId: 1,
    toWarehouseId: 2,
    timestamp: new Date("2026-03-09T10:15:00"),
    previousStatus: "Pending",
    newStatus: "At Warehouse",
    description: "Package arrived at West Coast Depot and is awaiting processing.",
  },
  {
    id: 4,
    packageId: 3,
    fromWarehouseId: 3,
    toWarehouseId: 4,
    timestamp: new Date("2026-03-08T16:45:00"),
    previousStatus: "In Transit",
    newStatus: "Delivered",
    description: "Package delivered successfully to final destination.",
  },
  {
    id: 5,
    packageId: 3,
    fromWarehouseId: 2,
    toWarehouseId: 3,
    timestamp: new Date("2026-03-08T09:00:00"),
    previousStatus: "At Warehouse",
    newStatus: "In Transit",
    description: "Package departed West Coast Depot en route to East Distribution.",
  },
  {
    id: 6,
    packageId: 4,
    fromWarehouseId: 4,
    toWarehouseId: 1,
    timestamp: new Date("2026-03-12T07:00:00"),
    previousStatus: "Pending",
    newStatus: "Pending",
    description: "Package registered at South Regional and queued for dispatch.",
  },
  {
    id: 7,
    packageId: 5,
    fromWarehouseId: 2,
    toWarehouseId: 4,
    timestamp: new Date("2026-03-11T11:20:00"),
    previousStatus: "In Transit",
    newStatus: "Exception",
    description: "Delivery exception: address not found. Package held at South Regional.",
  },
];
